### ISSUE TITLE
This link is dead: https://github.com/msurdi/wipku

### ISSUE THREAD

**Issue by benderillo** [msurdi/msurdi.github.io#1]
Hi
I came across this post:
https://msurdi.github.io/posts/4-salted-passwordless-authentication/

And was curious to look at the source code linked by this url: https://github.com/msurdi/wipku but it leads to 404

Any chance you can provide working link?
Thanks!

**Comment by msurdi** [comment]
Hi @benderillo

Sorry for that. I've just updated the blog post and linked to [this repo](https://github.com/msurdi/taskittous) which has this approach implemented.

Take it with a grain of salt. Remember I'm not a security expert and I'm not 100% sure this is safe enough to do in a real production environment, if that's your case.

Hope it helps.
